# Generated by Django 3.0.2 on 2021-06-06 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0006_auto_20200825_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 16, 42, 41, 978779, tzinfo=utc), verbose_name='수정일'),
        ),
    ]
